### ISSUE TITLE
wisata & menu restaurant

### ISSUE THREAD

**Issue by savinasz** [ibnu009/jelajahin-web#2]
1. update wisata (input provinsi dll agar muncul data yg dipilih, latitude dan longitude agar muncul data yg telah terpilih)
2. menu restaurant (add menu restaurant agar data yg masuk dan tampil sesuai dengan uuid_restaurantnya)

**Comment by destroylord** [comment]
Menu restaurant udah solved

**Comment by destroylord** [comment]
> 1. update wisata (input provinsi dll agar muncul data yg dipilih, latitude dan longitude agar muncul data yg telah terpilih)
> 2. menu restaurant (add menu restaurant agar data yg masuk dan tampil sesuai dengan uuid_restaurantnya)

menu restaurant udah solved
